Repository VulnerabilityHistoryProject/vulnerability-history, pull requests merged in 2020-09, with the labels that each got.

#785 Vulnerability "short_descriptions" are the first sentence of the description (#749)
  app/controllers/vulnerabilities_controller.rb
  app/models/filepath.rb
  app/models/vulnerability.rb
  db/schema.rb
  lib/loaders/vulnerability_loader.rb
  test/controllers/vulnerabilities_controller_test.rb
Labels: enhancement

#776 Prevent FOUC on the top bar (#775)
  app/frontend/global/vhp.scss
  app/views/layouts/application.html.erb
Labels: bug

#773 Better pagination on vulnerability#index
  app/controllers/application_controller.rb
  app/controllers/tags_controller.rb
  app/controllers/vulnerabilities_controller.rb
  app/frontend/global/vhp.scss
  app/frontend/vulnerabilities/index.js
  app/frontend/vulnerabilities/vulnTable.js
  app/models/tag.rb
  app/views/articles/index.html.erb
  app/views/commits/index.html.erb
  app/views/commits/show.html.erb
  app/views/developers/index.html.erb
  app/views/developers/show.html.erb
  app/views/filepaths/index.html.erb
  app/views/filepaths/show.html.erb
  app/views/layouts/application.html.erb
  app/views/tags/index.html.erb
  app/views/tags/show.html.erb
  app/views/vulnerabilities/_index_table.html.erb
  app/views/vulnerabilities/index.html.erb
  app/views/vulnerabilities/show.html.erb
  app/views/welcome/index.html.erb
  config/webpack/environment.js
Labels: enhancement, javascript, refactor

#789 Fixing & refactoring unit tests
  lib/event_generators/fix_events.rb
  lib/event_generators/same_cwe_events.rb
  lib/event_generators/same_directory_events.rb
  lib/event_generators/vcc_events.rb
  lib/event_generators/weekly_report_events.rb
  lib/tasks/clear.rake
  lib/tasks/optimize.rake
  test/fixtures/events.yml
  test/lib/event_generators/all_vulnerability_events_test.rb
  test/lib/event_generators/fix_events_test.rb
  test/lib/event_generators/release_events_test.rb
  test/lib/event_generators/same_cwe_events_test.rb
  test/lib/event_generators/same_directory_events_test.rb
  test/lib/event_generators/vcc_events_test.rb
  test/lib/event_generators/vulnerability_events_test.rb
  test/models/event_test.rb
  test/test_helper.rb
Labels: dev infrastructure, refactor

#801 Article bylines (#705)
  app/frontend/global/vhp.scss
  app/views/articles/show.html.erb
  db/schema.rb
  lib/loaders/article_loader.rb
  test/fixtures/articles.yml
Labels: enhancement

#802 Add OpenGraph meta tags for SEO (#790)
  app/assets/images/angler-fish-512x512.png
  app/assets/images/angler-fish-og-image.png
  app/views/layouts/application.html.erb
  app/views/tags/show.html.erb
Labels: enhancement

#800 Rework filepaths#index map visual (#699, #652, #671, #716, #672)
  app/assets/images/offender-map-loading.svg
  app/frontend/filepaths/filepaths.scss
  app/frontend/filepaths/index.js
  app/frontend/filepaths/offender_map.js
  app/frontend/filepaths/offender_table.js
  app/frontend/foundation_config/_settings.scss
  app/frontend/global/vhp.scss
  app/models/filepath.rb
  app/views/filepaths/_offenders_articles.html.erb
  app/views/filepaths/_offenders_map.html.erb
  app/views/filepaths/_offenders_table.html.erb
  app/views/filepaths/index.html.erb
Labels: enhancement, refactor

#805 Minor version bumps for security
  Gemfile.lock
  yarn.lock
Labels: bug
