Repository VulnerabilityHistoryProject/vulnerability-history, pull requests merged in 2020-10, with the labels that each got.

#799 Make DataBuilder for all project rake task (#783)
  lib/data_builder.rb
  lib/tasks/chromium.rake
  lib/tasks/data.rake
  lib/tasks/httpd.rake
  lib/tasks/struts.rake
  lib/tasks/tomcat.rake
Labels: refactor, ruby

#815 Rework known offenders table
  app/frontend/filepaths/offender_map.js
  app/frontend/filepaths/offender_table.js
  app/frontend/foundation_config/_settings.scss
  app/frontend/global/dataToPrettyStrings.js
  app/frontend/global/vhp.scss
  app/frontend/packs/application.js
  app/models/filepath.rb
  app/views/filepaths/_offenders_table.html.erb
  app/views/filepaths/index.html.erb
Labels: enhancement

#819 Switch to Heroku Release Phase
  Procfile
  app.json
  config/environments/production.rb
  lib/event_generators/same_directory_events.rb
  lib/event_generators/weekly_report_events.rb
Labels: dev infrastructure
