Repository VulnerabilityHistoryProject/vulnerability-history, pull requests merged in 2023-05, with the labels that each got.

#1123 Fix offenders vulnerabilities query
  app/models/filepath.rb
Labels: bug

#1030 Data version footer #971
  app/controllers/about_controller.rb
  app/models/vhp_metadata.rb
  app/views/about/version.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  db/schema.rb
  lib/data_builder.rb
  lib/tasks/clear.rake
  lib/tasks/data.rake
  lib/version.rb
  package-lock.json
  package.json
  test/controllers/about_controller_tests.rb
  test/models/vhp_metadata_test.rb
  yarn.lock
Labels: enhancement

#1130 Homepage redesign
  app/assets/images/angler-big-dark.png
  app/assets/images/angler-big-light.png
  app/assets/images/angler-fish-5.png
  app/assets/images/angler-fish-dark.png
  app/assets/images/angler-fish-nav.png
  app/assets/images/clouds-dark.png
  app/assets/images/computer-center.png
  app/assets/images/dark-background-water.png
  app/assets/images/deep-thought.png
  app/assets/images/footer-fish-dark.png
  app/assets/images/footer-fish-light.png
  app/assets/images/hands.png
  app/assets/images/help-us-bg-dark-mobile.png
  app/assets/images/help-us-bg-dark.png
  app/assets/images/help-us-bg-light-mobile.png
  app/assets/images/help-us-bg-light.png
  app/assets/images/jellyfish-dark.png
  app/assets/images/jellyfish-light.png
  app/assets/images/keyboard-dark.png
  app/assets/images/keyboard-light.png
  app/assets/images/laptop.png
  app/assets/images/laughing.png
  app/assets/images/learn-bg-dark.png
  app/assets/images/learn-bg-light.png
  app/assets/images/sea-light.png
  app/assets/images/surface_water.png
  app/assets/images/what-now-angler-fish-dark.png
  app/assets/images/what-now-angler-fish.png
  app/assets/images/what-now-bg-dark.png
  app/assets/images/what-now-bg.png
  app/assets/javascripts/global/darkMode.js
  app/assets/javascripts/vhp.js
  app/assets/stylesheets/foundation_config/_settings.scss
  app/assets/stylesheets/foundation_config/foundation_and_overrides.scss
  app/assets/stylesheets/vhp.scss
  app/views/layouts/application.html.erb
  app/views/welcome/index.html.erb
Labels: enhancement

#1107 Issue 1091 tagoverlaps
  app/assets/config/manifest.js
  app/assets/javascripts/routes.js
  app/controllers/tags_controller.rb
  app/models/tag.rb
  config/routes.rb
  public/openapi.yml
  test/controllers/tags_controller_test.rb
  test/fixtures/tags.yml
  test/fixtures/vulnerabilities.yml
  test/fixtures/vulnerability_tags.yml
  test/models/tag_test.rb
Labels: tag-trends
